package BasicCalculator;
/**
 * @author Tamanna Qureshi
 */
public class BasicCalculator extends javax.swing.JFrame {

    /**
     * Creates new form BasicCalculator
     */
    String text = "0";
    CalcFunctions f= new CalcFunctions(text);
            
    public BasicCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        One = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Calc = new javax.swing.JTextField();
        Three = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Decimal = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Equal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Calculator");
        setMinimumSize(new java.awt.Dimension(195, 211));

        One.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        One.setText("1");
        One.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OneMouseClicked(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });

        Two.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Two.setText("2");
        Two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwoMouseClicked(evt);
            }
        });

        Calc.setEditable(false);
        Calc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Calc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Calc.setText("0");

        Three.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Three.setText("3");
        Three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThreeMouseClicked(evt);
            }
        });

        Four.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Four.setText("4");
        Four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FourMouseClicked(evt);
            }
        });

        Five.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Five.setText("5");
        Five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiveMouseClicked(evt);
            }
        });

        Six.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Six.setText("6");
        Six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SixMouseClicked(evt);
            }
        });

        Seven.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Seven.setText("7");
        Seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SevenMouseClicked(evt);
            }
        });

        Eight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Eight.setText("8");
        Eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EightMouseClicked(evt);
            }
        });

        Nine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nine.setText("9");
        Nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NineMouseClicked(evt);
            }
        });

        Zero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Zero.setText("0");
        Zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZeroMouseClicked(evt);
            }
        });

        Decimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Decimal.setText(".");
        Decimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecimalMouseClicked(evt);
            }
        });

        Plus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Plus.setText("+");
        Plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlusMouseClicked(evt);
            }
        });

        Minus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Minus.setText("-");
        Minus.setPreferredSize(new java.awt.Dimension(43, 25));
        Minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusMouseClicked(evt);
            }
        });

        Divide.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Divide.setText("/");
        Divide.setPreferredSize(new java.awt.Dimension(43, 25));
        Divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DivideMouseClicked(evt);
            }
        });

        Multiply.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Multiply.setText("x");
        Multiply.setPreferredSize(new java.awt.Dimension(43, 25));
        Multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplyMouseClicked(evt);
            }
        });

        Equal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Equal.setText("=");
        Equal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EqualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Zero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Seven)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Eight)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Four, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(One, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Two)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Three)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Plus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Five)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Six)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(Clear))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Calc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(One)
                    .addComponent(Two)
                    .addComponent(Three)
                    .addComponent(Plus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Four)
                    .addComponent(Five)
                    .addComponent(Six)
                    .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seven)
                    .addComponent(Eight)
                    .addComponent(Nine)
                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zero)
                    .addComponent(Decimal)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneMouseClicked
        Calc.setText(f.insertNum("1"));
    }//GEN-LAST:event_OneMouseClicked

    private void TwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoMouseClicked
        Calc.setText(f.insertNum("2"));
    }//GEN-LAST:event_TwoMouseClicked

    private void ThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeMouseClicked
        Calc.setText(f.insertNum("3"));
    }//GEN-LAST:event_ThreeMouseClicked

    private void FourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourMouseClicked
        Calc.setText(f.insertNum("4"));
    }//GEN-LAST:event_FourMouseClicked

    private void FiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveMouseClicked
        Calc.setText(f.insertNum("5"));
    }//GEN-LAST:event_FiveMouseClicked

    private void SixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixMouseClicked
        Calc.setText(f.insertNum("6"));
    }//GEN-LAST:event_SixMouseClicked

    private void SevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenMouseClicked
        Calc.setText(f.insertNum("7"));
    }//GEN-LAST:event_SevenMouseClicked

    private void EightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightMouseClicked
        Calc.setText(f.insertNum("8"));
    }//GEN-LAST:event_EightMouseClicked

    private void NineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineMouseClicked
        Calc.setText(f.insertNum("9"));
    }//GEN-LAST:event_NineMouseClicked

    private void ZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroMouseClicked
        Calc.setText(f.insertNum("0"));
    }//GEN-LAST:event_ZeroMouseClicked

    private void DecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecimalMouseClicked
        Calc.setText(f.insertNum("."));
    }//GEN-LAST:event_DecimalMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        Calc.setText(f.clear());
    }//GEN-LAST:event_ClearMouseClicked

    private void PlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusMouseClicked
        f.calcu("+");
    }//GEN-LAST:event_PlusMouseClicked

    private void MinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinusMouseClicked
        f.calcu("-");
    }//GEN-LAST:event_MinusMouseClicked

    private void DivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DivideMouseClicked
        f.calcu("/");
    }//GEN-LAST:event_DivideMouseClicked

    private void MultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplyMouseClicked
        f.calcu("x");
    }//GEN-LAST:event_MultiplyMouseClicked

    private void EqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMouseClicked
        Calc.setText(f.Equal());
    }//GEN-LAST:event_EqualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Calc;
    public javax.swing.JButton Clear;
    public javax.swing.JButton Decimal;
    public javax.swing.JButton Divide;
    public javax.swing.JButton Eight;
    public javax.swing.JButton Equal;
    public javax.swing.JButton Five;
    public javax.swing.JButton Four;
    public javax.swing.JButton Minus;
    public javax.swing.JButton Multiply;
    public javax.swing.JButton Nine;
    public javax.swing.JButton One;
    public javax.swing.JButton Plus;
    public javax.swing.JButton Seven;
    public javax.swing.JButton Six;
    public javax.swing.JButton Three;
    public javax.swing.JButton Two;
    public javax.swing.JButton Zero;
    // End of variables declaration//GEN-END:variables
}
